### ISSUE TITLE
Crash NPE

### ISSUE THREAD

**Issue by TechStack** [FireBall1725/Graves#31]
I was flying around the world and go this error crashing the server today. 
Each time the area is loaded the server crashes again :( 

Cheers :)

Stack trace

Time: 2/28/16 6:36 PM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
        at com.fireball1725.graves.tileentity.TileEntityGraveStone.func_145844_m(TileEntityGraveStone.java:32)
        at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:591)
        at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:292)
        at net.minecraft.world.World.func_72866_a(World.java:1862)
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:700)
        at net.minecraft.world.World.func_72870_g(World.java:1831)
        at net.minecraft.world.World.func_72939_s(World.java:1663)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:545)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
        at java.lang.Thread.run(Thread.java:745)

**Comment by TechStack** [comment]
Adding Build Number to report.

Graves-1.8.9-B42-universal.jar   Crash is on server side.

Players near the gravestone are unable to login without crashing the server :(

**Comment by FireBall1725** [comment]
Ok thanks for the crash report, I will look into what is causing this.

**Comment by TechStack** [comment]
No rush from my side i was able to rollback to an older version for now :)
B39-universal seems to work fine. Maybe that will help pinpoint the change.

**Comment by FusionLord** [comment]
@TechStack [b43](http://minecraft.curseforge.com/projects/graves/files/2284600) is up, if you could let us know if that fixed your NPE Crash that would be great!

**Comment by TechStack** [comment]
Thanks, I'll give it a try and provide feedback tonight hopefully.

**Comment by TechStack** [comment]
That did the trick.
I updated to latest b45 and went back to the location of the previous crash and it was happy

Produced this instead of the crash as expected.
[14:45:24] [Server thread/INFO] [Graves]: Gravestone (null) at W=world X=-39 Y=32 Z=32
[14:46:43] [Server thread/INFO] [Graves]: Gravestone (null) at W=world X=-39 Y=32 Z=32

Thanks!

**Comment by FusionLord** [comment]
Good to know :) :+1:
