### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by utoc** [FireBall1725/Graves#52]
Pastebin here: http://pastebin.com/xUsHSNLv

```
Caused by: java.lang.ClassNotFoundException: com.fireball1725.graves.proxy.ServerProxy
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
```

Happened immediately after updating dedicated server pack upon startup.

Using graves-1.10.2-b17-universal

**Comment by FusionLord** [comment]
I'm on it.

**Comment by FusionLord** [comment]
Fixed in b18.

**Comment by utoc** [comment]
Tested today, working correctly.
