### ISSUE TITLE
Crash after block is broken in SMP

### ISSUE THREAD

**Issue by TechStack** [FireBall1725/Graves#9]
HI fierball :D 

I added your mod to my server and it seems the clients will crash when someone else breaks a grave.

I'm guessing the TESR needs to check if its still is a grave block in that spot before getting the property direction 
Hope this helps.
Fellow modder Techstack !

Crash report

Time: 1/24/16 2:11 AM
Description: Rendering Block Entity

java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} as it does not exist in BlockState{block=minecraft:air, properties=[]}
    at net.minecraft.block.state.BlockState$StateImplementation.func_177229_b(BlockState.java:137)
    at com.fireball1725.graves.client.render.TileEntityHeadStoneRenderer.func_180535_a(TileEntityHeadStoneRenderer.java:32)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_178469_a(SourceFile:114)
    at net.minecraft.client.renderer.tileentity.TileEntityRendererDispatcher.func_180546_a(SourceFile:102)
    at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:677)
    at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1315)
    at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1229)
    at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1057)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by FireBall1725** [comment]
That should be fixed in version b29.  Can you let me know if that fixes the issue?

**Comment by TechStack** [comment]
I asked around last night & we haven't had the crash in the last couple of days since the update. 
Thanks for the fix!
